---
title: "bridges"
format: html
editor: visual
---

## lib

```{r}

library(broom)
library(readxl)
library(lubridate)
library(dplyr)
library(tidyverse)
library(scales)
library(mapproj)
```

## data

```{r}
theme_set(theme_light())
bridges <- read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-11-27/baltimore_bridges.csv")
```

## cleaning

```{r}
bridges <- bridges |> 
  select(-vehicles)
bridges <- bridges |>
  replace_na(list(responsibility="Other")) |>
  mutate(inspection_yr=inspection_yr+2000,decade=10*(yr_built %/%10),
         responsibility=fct_lump(responsibility,4))
  
```

## analyzing

```{r}
bridges |> 
  filter(yr_built>=1900) |> 
  count(decade=10*(yr_built %/%10),sort=T) |> 
  ggplot(aes(decade,n))+
           geom_line()+
  expand_limits(y=0)
```

How does the condition of bridges depend on how old it is?

```{r}
bridges |> 
  filter(yr_built>=1900) |> 
  group_by(decade) |> 
  summarise(pct_good=mean(bridge_condition=="Good"),
            total=n()) |> 
  ggplot(aes(decade,pct_good))+
  geom_line()+
  scale_y_continuous(labels=percent_format())
  #Most bridges built before 1970 would not be consider being in good condition and it doesnt matter how long before 1970 they were built. Vast majority of bridges built since 2000 are in good condition.

bridges |> 
  filter(yr_built>=1900) |> 
  replace_na(list(responsibility="Other")) |> 
  group_by(responsibility=fct_lump(responsibility,4),decade,sort = T) |>
  summarise(pct_good=mean(bridge_condition=="Good"),
            total=n()) |> 
  ggplot(aes(decade,pct_good,color=responsibility))+
  geom_line()+
  scale_y_continuous(labels=percent_format())+
  expand_limits(y=0)


bridges |> 
  filter(yr_built>=1900) |> 
  replace_na(list(responsibility="Other")) |> 
  group_by(responsibility=fct_lump(responsibility,4),decade,sort = T) |>
  summarise(pct_good=mean(bridge_condition=="Good"),
            total=n()) |> 
  filter(responsibility!="Other") |> 
  ggplot(aes(decade,pct_good,color=responsibility))+
  geom_line()+
  scale_y_continuous(labels=percent_format())+
  expand_limits(y=0)+
  labs(title="condition of bridges rated good")
#The County Highway Agency consistently has the most bridges rated "Good" from before 1970.
#State Toll Authority is underperforming in comperison to other agencies.
```

owner and responsibility pairs

```{r}
bridges |>
  replace_na(list(responsibility="Other")) |> 
  count(responsibility=fct_lump(responsibility,4),sort = T) |> 
  mutate(responsibility=fct_reorder(responsibility,n)) |> 
  ggplot(aes(responsibility,n))+
  geom_col()+
  coord_flip()

bridges |> 
  filter(responsibility!=owner)
# 5 cases where owner != responsibility so no significant difference for our analysis

bridges |> 
  group_by(responsibility)

bridges |>
  replace_na(list(responsibility="Other")) |> 
  count(responsibility=fct_lump(responsibility,4),decade,sort = T) |> 
  mutate(responsibility=fct_reorder(responsibility,n))
```

```{r}
bridges |> 
  ggplot(aes(avg_daily_traffic))+
  geom_histogram()+
  scale_x_log10(labels=comma_format())
```

```{r}
bridges |> 
  filter(yr_built >= 1990) |> 
  group_by(traffic_cat=cut(avg_daily_traffic,c(0,1000,10000,Inf),labels=c("<1000","1000-10000","10000+"),
          )) |> 
  summarise(pct_good=mean(bridge_condition=="Good"),
            total=n())
#Maybe there is a relationship between maintanence frequency and average daily traffic. Bridges more popular tend to have more maintanence
```

```{r}
#Mapy jebane
bridges |> 
  ggplot(aes(long,lat,color=avg_daily_traffic))+
  borders("state",regions = "Maryland")+
  geom_point()+
  scale_color_gradient2(low="blue",high="red", midpoint = log10(median(bridges$avg_daily_traffic)),
                        trans="log10",
                        labels=comma_format())+
  theme_void()+
  coord_map()



   
   bridges |> 
  ggplot(aes(long,lat,color=bridge_condition))+
  borders("state",regions = "Maryland")+
  geom_point(size=1)+
  theme_void()+
  coord_map()
      
       bridges |> 
  ggplot(aes(long,lat,color=bridge_condition))+
  borders("state",regions = "Maryland")+
  geom_point(size=1)+
  theme_void()+
  coord_map()
       
  bridges |> 
  ggplot(aes(long,lat,color=county))+
  borders("state",regions = "Maryland")+
  geom_point(size=1)+
  theme_void()+
  coord_map()
  
bridges |> 
  filter(yr_built>=1900) |> 
  group_by(county,decade,sort = T) |>
  summarise(pct_good=mean(bridge_condition=="Good"),
            total=n()) |> 
  ggplot(aes(decade,pct_good,color=county))+
geom_line()+
  scale_y_continuous(labels=percent_format())+
  expand_limits(y=0)
```

## Effect of county responsibility,traffic and time on bridge condition

```{r}
bridges |>
  mutate(good=bridge_condition=="Good") |> 
  glm(good~yr_built,data=env,family="binomial")

augment(model,bridges)
```
